### ISSUE TITLE
Создать описание привязки экранных форм к REST-сервисам

### ISSUE THREAD

**Issue by inspired-geek** [SiriusSochi/front#1]
Необходимо разработать описание связи экранов с бэкендом.
Результат нужен в виде таблицы

Экран | Действие | URL сервиса | Разработан | Привязан
------- | -----------|----------------|--------------|-------------
Логин | Вход | https://sso.portal.rzhd.ml/auth/realms/rzhd-realm | ✔ | ✔

**Comment by Apavele** [comment]
[back.xlsx](https://github.com/SiriusSochi/front/files/2213065/back.xlsx)

**Comment by Apavele** [comment]
Экраны
