### ISSUE TITLE
Реализовать функционал отправки сообщения

### ISSUE THREAD

**Issue by inspired-geek** [SiriusSochi/front#12]
Использовать для этого сервис https://sirius.rzhd.ml/api/educ/sendMessage

**Comment by Fr1m3n** [comment]
POST https://sirius.rzhd.ml/api/educ/sendMessage/6f69cd5f-1b41-4db2-b2cf-fe945b287a10
Body:
{
	"text": "Привет"
}

Ответ(созданное сообщение):
{
    "id": 111216,
    "text": "Привет",
    "sender": 88325,
    "recevier": 0,
    "date": "2018-07-21T14:43:59.061+0000",
    "link": 111212
}

**Comment by Apavele** [comment]
готово
