### ISSUE TITLE
Реализовать функционал получения сообщений

### ISSUE THREAD

**Issue by inspired-geek** [SiriusSochi/front#13]
Для этого использовать сервис https://sirius.rzhd.ml/api/educ/getMessage

**Comment by Fr1m3n** [comment]
GET https://sirius.rzhd.ml/api/educ/getMessages/6f69cd5f-1b41-4db2-b2cf-fe945b287a10

Ответ:
[
    {
        "id": 111216,
        "text": "Привет",
        "sender": 88325,
        "recevier": 0,
        "date": "2018-07-21T14:43:59.061+0000",
        "link": 111212
    },
    {
        "id": 111217,
        "text": "Чё, как?",
        "sender": 88325,
        "recevier": 0,
        "date": "2018-07-21T14:46:18.446+0000",
        "link": 111212
    },
    {
        "id": 111218,
        "text": "И тебе привет, всё хорошо!",
        "sender": 55903,
        "recevier": 88325,
        "date": "2018-07-21T14:49:29.739+0000",
        "link": 111212
    }
]

**Comment by Apavele** [comment]
готово
