### ISSUE TITLE
Переход в меню из чата. Плывёт верстка.

### ISSUE THREAD

**Issue by BigTonyMoscow** [SiriusSochi/front#19]
![2018-07-21 11 35 15](https://user-images.githubusercontent.com/40933912/43033852-66688a78-8cda-11e8-8538-14ac845cc4c4.jpg)
![2018-07-21 11 35 09](https://user-images.githubusercontent.com/40933912/43033853-66872794-8cda-11e8-9a8c-d6b17a027714.PNG)

**Comment by inspired-geek** [comment]
Воспроизводится только на iphone x. В MVP не будем его поддерживать.
