### ISSUE TITLE
нет функционала у кнопки "выход"

### ISSUE THREAD

**Issue by highlewel** [SiriusSochi/front#28]
![lnt0kuwvtsy](https://user-images.githubusercontent.com/40933569/43034154-bcee3bea-8cdf-11e8-94ef-06616b3fcd36.jpg)
xiaomi Redmi 5 plus 
android v. 7.1.2.

**Comment by highlewel** [comment]
![zid-r8r8zds](https://user-images.githubusercontent.com/40933569/43045173-407f0764-8dbc-11e8-826a-f584f9aab065.jpg) 
не полностью происходит выход из профиля

**Comment by inspired-geek** [comment]
Нужно выходить в кейлоаке.
[Документация](https://www.keycloak.org/docs/latest/securing_apps/index.html#logout)
В нашем случае адрес такой: https://sso.portal.rzhd.ml/auth/realms/rzhd-realm/protocol/openid-connect/logout?redirect_uri=ml.rzhd.portal.sso%3A%2Fcallback
