### ISSUE TITLE
Кодировка текста в кнопке сообщения при подтверждении завершения обучения

### ISSUE THREAD

**Issue by mariapimenova** [SiriusSochi/front#55]
При завершении обучения в сообщении выводится текст в неверной кодировке.

![image](https://user-images.githubusercontent.com/40933573/43045506-74bd01ec-8dc2-11e8-89da-0908d3211558.png)

**Comment by highlewel** [comment]
так же рамочка находится немного сверху , что мешает нам её увидеть без прокрутки экрана вверх.
