### ISSUE TITLE
Реализовать функционал установления связи между наставником и учеником

### ISSUE THREAD

**Issue by inspired-geek** [SiriusSochi/front#6]
Использовать для этого https://sirius.rzhd.ml/api/educ/link?id=guid_ученика

**Comment by inspired-geek** [comment]
Необходимы примеры запросов/ответов

**Comment by Fr1m3n** [comment]
По GET запросу на адрес:
 https://sirius.rzhd.ml/api/educ/link/b4b3280a-ab6c-4ece-82c8-761eeb7467a9
Ответ: 
{
    "id": 111200,
    "teacher": 88325,
    "pupil": 55894,
    "dateOfCreate": null,
    "dateOfEnd": "2018-07-20T12:26:47.221+0000",
    "inititator": 88325,
    "status": 1
}

**Comment by Razrpro** [comment]
a943546be698caa08e0921580ea5b7c631f6f2dd готово
